<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wat</string>
	</array>
	<key>name</key>
	<string>wasm</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;;[^\n]*</string>
			<key>name</key>
			<string>comment.line.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(module|func|import|export|param|result|start|memory|data|local)\b</string>
			<key>name</key>
			<string>keyword.other.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(i|f)(32|64)</string>
			<key>name</key>
			<string>support.type.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z\_\d]+</string>
			<key>name</key>
			<string>variable.language.wasm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.wasm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.wasm</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\()</string>
			<key>name</key>
			<string>punctuation.section.scope.begin.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\))</string>
			<key>name</key>
			<string>punctuation.section.scope.end.wasm</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.wasm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(call|get_local|set_local|drop)</string>
					<key>name</key>
					<string>support.function.keyword.wasm</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\.[a-z]+</string>
					<key>name</key>
					<string>support.function.call.wasm</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.wasm</string>
	<key>uuid</key>
	<string>3910C04C-8ADB-4FE6-A274-991F343930AE</string>
</dict>
</plist>
